//! Pure construction of what is sent to the WebView: the page, the files it
//! loads, and the script that asks it to render a diagram.

use crate::error::{Error, Result};
use std::borrow::Cow;

const HTML_TEMPLATE: &str = include_str!("../../assets/render.html");

/// mermaid's ESM build (`assets/mermaid/`), as `(relative path, content)`
/// sorted by path. Generated by `build.rs`.
static MERMAID_FILES: &[(&str, &[u8])] = include!(concat!(env!("OUT_DIR"), "/mermaid_files.rs"));

/// Escapes `<` and `>` to Unicode escapes for safe embedding inside `<script>`.
fn escape_for_script(s: &str) -> String {
    s.replace('<', "\\u003c").replace('>', "\\u003e")
}

/// Validates that `config_json` (if present) parses as a JSON object.
///
/// A `config_json` that isn't a valid JS object literal breaks
/// `mermaid.initialize()` in the WebView before it can signal readiness,
/// which would otherwise hang [`crate::render_stream`] forever instead of
/// returning an error.
pub(super) fn validate_config_json(config_json: Option<&str>) -> Result<()> {
    if let Some(s) = config_json {
        let value: serde_json::Value =
            serde_json::from_str(s).map_err(|e| Error::Config(e.to_string()))?;
        if !value.is_object() {
            return Err(Error::Config(format!("expected a JSON object, got: {s}")));
        }
    }
    Ok(())
}

pub(super) fn build_html(config_json: Option<&str>) -> String {
    let config_json = config_json.map_or_else(|| "{}".to_string(), escape_for_script);
    HTML_TEMPLATE.replace("{{CONFIG_JSON}}", &config_json)
}

/// What the custom protocol serves for `path`: the page at `/` (or
/// `/index.html`), and mermaid's ESM files by their path, which the page and
/// the files import relative to each other. `None` means not found.
pub(super) fn resource(path: &str, page: &str) -> Option<(Cow<'static, [u8]>, &'static str)> {
    match path.trim_start_matches('/') {
        "" | "index.html" => Some((Cow::Owned(page.as_bytes().to_vec()), "text/html")),
        file => MERMAID_FILES
            .binary_search_by(|(p, _)| (*p).cmp(file))
            .ok()
            .map(|i| (Cow::Borrowed(MERMAID_FILES[i].1), "text/javascript")),
    }
}

/// The script that asks the page to render diagram `id` (`content`). The page
/// reports the result back via IPC with the same `id`.
pub(super) fn render_script(id: usize, content: &str) -> String {
    // serde_json produces a valid JS string literal (escaping `"`, `\`,
    // control chars, U+2028/U+2029). evaluate_script bypasses the HTML parser,
    // so `</script>` does not need the extra escaping that build_html requires.
    let literal = serde_json::to_string(content).expect("serialize Mermaid block content");
    format!("renderMermaid({id}, {literal})")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mermaid_files_are_sorted_for_binary_search() {
        assert!(MERMAID_FILES.windows(2).all(|w| w[0].0 < w[1].0));
    }

    #[test]
    fn resource_serves_the_page_and_mermaid_files_only() {
        let page = "<html>page</html>";
        for path in ["/", "/index.html"] {
            let (body, ctype) = resource(path, page).unwrap();
            assert_eq!((&*body, ctype), (page.as_bytes(), "text/html"));
        }
        let (_, ctype) = resource("/mermaid.esm.min.mjs", page).unwrap();
        assert_eq!(ctype, "text/javascript");
        for path in ["/missing.mjs", "/../Cargo.toml", "/chunks", "/render.html"] {
            assert!(resource(path, page).is_none(), "{path}");
        }
    }

    #[test]
    fn page_imports_the_bundled_entry() {
        let html = build_html(None);
        assert!(html.contains(r#"import mermaid from "./mermaid.esm.min.mjs""#));
        assert!(resource("/mermaid.esm.min.mjs", "").is_some());
    }

    /// Every relative import (`"./x.mjs"`) in every file must resolve to a
    /// bundled file; a chunk missed by util/update-mermaid.sh would otherwise
    /// only fail when a diagram needs it.
    #[test]
    fn all_relative_imports_resolve() {
        for (path, content) in MERMAID_FILES {
            let dir = path.rsplit_once('/').map_or("", |(d, _)| d);
            let text = String::from_utf8_lossy(content);
            for (i, _) in text.match_indices("\"./") {
                let rest = &text[i + 3..];
                let Some(end) = rest.find('"') else { continue };
                let spec = &rest[..end];
                if !spec.ends_with(".mjs") {
                    continue;
                }
                let target = if dir.is_empty() {
                    spec.to_string()
                } else {
                    format!("{dir}/{spec}")
                };
                assert!(
                    resource(&target, "").is_some(),
                    "{path} imports ./{spec}, which is not bundled"
                );
            }
        }
    }

    #[test]
    fn render_script_passes_content_as_a_js_string_literal() {
        assert_eq!(
            render_script(3, "graph LR\n  A[\"</script>\"]"),
            r#"renderMermaid(3, "graph LR\n  A[\"</script>\"]")"#
        );
    }

    #[test]
    fn escape_for_script_escapes_angle_brackets() {
        assert_eq!(
            escape_for_script("</script><script>"),
            "\\u003c/script\\u003e\\u003cscript\\u003e"
        );
    }

    #[test]
    fn validate_config_json_accepts_none_and_objects() {
        assert!(validate_config_json(None).is_ok());
        assert!(validate_config_json(Some("{}")).is_ok());
        assert!(validate_config_json(Some(r#"{"theme":"dark"}"#)).is_ok());
    }

    #[test]
    fn validate_config_json_rejects_non_objects_and_invalid_json() {
        assert!(matches!(
            validate_config_json(Some("not json")),
            Err(Error::Config(_))
        ));
        assert!(matches!(
            validate_config_json(Some("[1, 2, 3]")),
            Err(Error::Config(_))
        ));
        assert!(matches!(
            validate_config_json(Some(r#""a string""#)),
            Err(Error::Config(_))
        ));
    }

    #[test]
    fn build_html_defaults_to_empty_config() {
        let html = build_html(None);
        assert!(html.contains("...{}"));
    }

    #[test]
    fn build_html_with_config_json() {
        let html = build_html(Some(r#"{"flowchart":{"curve":"basis"}}"#));
        assert!(html.contains(r#"...{"flowchart":{"curve":"basis"}}"#));
    }

    #[test]
    fn build_html_escapes_closing_script_tags_in_config_json() {
        // Embedding `</script>` must not break out of the script block.
        let html = build_html(Some(r#"{"theme":"</script>"}"#));
        assert!(!html.contains("</script>\""));
        assert!(html.contains("\\u003c/script\\u003e"));
    }
}
